name: Monthly iDigBio Charts

on:
  schedule:
    # Runs at 02:00 UTC on the 1st of every month
    - cron: '0 2 1 * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true   # <— ensure the GITHUB_TOKEN can push back

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests pandas matplotlib plotly

      - name: Generate charts
        run: |
          python update_charts.py --recordset 7b0809fb-fd62-4733-8f40-74ceb04cbcac

      - name: Commit & push charts
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/charts/
          git commit -m "Monthly charts for $(date +'%Y-%m-%d')" || echo "No changes"
          git push
